### ISSUE TITLE
Error in rclone-authenticate-remote.yml: "Failed to backend: didn't find section in config file"

### ISSUE THREAD

**Issue by tquin** [tigattack/ansible-rclone-rc-remotes#1]
Hi,

I've recently hit an issue with this role in the "Check rclone authentication" step. I'm running rclone in its `rc` server mode [in a docker instance](https://rclone.org/install/#docker), so the path to `rclone.conf` on the host is not the same as in the container. The container has its config directory mounted in an separate area of the host filesystem (`/docker/rclone/config/rclone.conf`), not in the default of `~/.config/` or `/root/.config/`.

My understanding of the issue here is that the steps in `rclone-create-remote.yml` succeed because they use the `uri` module to hit the `rc` daemon, while in `rclone-authenticate-remote.yml` the `rclone` CLI is used directly instead. For my setup, the `rc` daemon responds from within the Docker container, but the second step using the CLI runs directly on the host in a different context.

My specific implementation is at: https://github.com/tquin/ansible/tree/main/roles/rclone_backup. I didn't notice this issue before [this commit](https://github.com/tigattack/ansible-rclone-rc-remotes/commit/4e08f4b5e54bab84f41862603b87a658dd62590f) because errors at this step were ignored, but I think the issue still existed silently before then.

The full error message I get (tested on Debian, Ubuntu, and Fedora):
```
TASK [tigattack.rclone_rc_remotes : Check rclone authentication] ******************************
fatal: [ansiblevm-debian12]: FAILED! => {"changed": false, "cmd": ["rclone", "backend", "drives", "azure-crypt:"], "delta": "0:00:00.043037", "end": "2024-01-03 20:41:09.399271", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2024-01-03 20:41:09.356234", "stderr": "2024/01/03 20:41:09 NOTICE: Config file \"/root/.config/rclone/rclone.conf\" not found - using defaults\n2024/01/03 20:41:09 Failed to backend: didn't find section in config file", "stderr_lines": ["2024/01/03 20:41:09 NOTICE: Config file \"/root/.config/rclone/rclone.conf\" not found - using defaults", "2024/01/03 20:41:09 Failed to backend: didn't find section in config file"], "stdout": "", "stdout_lines": []}
```

Is it possible to standardise the role to always use the exposed `rc` endpoint rather than mixing and matching with the CLI, in order to be agnostic to the way that daemon is hosted?

Cheers!

**Comment by tigattack** [comment]
Good spot, thank you. I no longer recall if I had a reason for this inconsistency or if it was purely an oversight, so I'll look at replacing the `rclone backend` commands with a call to the [`backend/command`](https://rclone.org/rc/#backend-command) RC endpoint and let you know.

**Comment by tigattack** [comment]
Hey @tquin, sorry for the delay! Could you try the changes in #2 and see if that solves your issue?

**Comment by tquin** [comment]
Hey @tigattack, happy to report everything looks to be working in my test envs using #2, so thank you for that. Cheers!

**Comment by tigattack** [comment]
Great, thanks for checking!
